Repository atereshkov/photomap, pull requests merged in 2021-06, with the labels that each got.

#54 Bugfix/52 Fix authentication
  PhotoMap/Core/Base/Controllers/BaseViewController.swift
  PhotoMap/Core/Base/Coordinators/TabBarCoordinator.swift
  PhotoMap/Core/Base/Errors/AlertError.swift
  PhotoMap/Core/Base/Errors/ResponseError.swift
  PhotoMap/Core/Base/Validation/PasswordValidation/PasswordValidator.swift
  PhotoMap/Core/Views/ErrorTextField.swift
  PhotoMap/Features/Auth/Authentication.storyboard
  PhotoMap/Features/Auth/Controllers/SignInViewController.swift
  PhotoMap/Features/Auth/Controllers/SignUpViewController.swift
  PhotoMap/Features/Auth/Coordinators/AuthCoordinator.swift
  PhotoMap/Features/Auth/Coordinators/AuthCoordinatorType.swift
  PhotoMap/Features/Auth/ViewModels/SignInViewModel/SignInViewModel.swift
  PhotoMap/Features/Auth/ViewModels/SignInViewModel/SignInViewModelType.swift
  PhotoMap/Features/Auth/ViewModels/SignUpViewModel/SignUpViewModel.swift
  PhotoMap/Features/Auth/ViewModels/SignUpViewModel/SignUpViewModelType.swift
  PhotoMap/Resources/Localization/en.lproj/Localizable.strings
  PhotoMap/Resources/Localization/ru.lproj/Localizable.strings
  PhotoMapTests/Mocks/Coordinators/AuthCoordinatorMock.swift
  PhotoMapTests/Utility/Validation/PasswordValidatorTests.swift
  PhotoMapTests/ViewModels/SignInViewModelTests.swift
  strings.swift
Labels: bug, improvement

#58 Bugfix/57 Sign in and sign up unit tests
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/App/SceneDelegate.swift
  PhotoMap/Core/Base/Validation/PasswordValidation/PasswordValidator.swift
  PhotoMap/Features/Auth/ViewModels/SignInViewModel/SignInViewModel.swift
  PhotoMap/Features/Auth/ViewModels/SignUpViewModel/SignUpViewModel.swift
  PhotoMapTests/Mocks/Coordinators/AuthCoordinatorMock.swift
  PhotoMapTests/Mocks/Services/AuthUserServiceMock.swift
  PhotoMapTests/ViewModels/SignInViewModelTests.swift
  PhotoMapTests/ViewModels/SignUpViewModelTests.swift
Labels: improvement

#56 Feature/30 category screen
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap.xcodeproj/xcshareddata/xcschemes/PhotoMapTests.xcscheme
  PhotoMap/App/SceneDelegate.swift
  PhotoMap/Core/Base/Models/Category.swift
  PhotoMap/Core/Base/Models/Marker.swift
  PhotoMap/Features/Category/Category.storyboard
  PhotoMap/Features/Category/Controllers/CategoryCell.swift
  PhotoMap/Features/Category/Controllers/CategoryViewController.swift
  PhotoMap/Features/Category/Coordinators/CategoryCoordinator.swift
  PhotoMap/Features/Category/ViewModels/CategoryViewModel.swift
  PhotoMap/Features/Category/ViewModels/CategoryViewModelType.swift
  PhotoMap/Features/Timeline/Controllers/TimelineViewController.swift
  PhotoMap/Features/Timeline/Coordinators/TimelineCoordinator.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModelType.swift
  PhotoMap/Resources/Localization/en.lproj/Localizable.strings
  PhotoMap/Resources/Localization/ru.lproj/Localizable.strings
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMap/Service/FirestoreService/FirestoreServiceType.swift
  PhotoMapTests/Mocks/Coordinators/TimelineCoordinatorMock.swift
  PhotoMapTests/Mocks/Services/FirestoreServiceMock.swift
  PhotoMapTests/ViewModels/CategoryViewModelTests.swift
  PhotoMapTests/ViewModels/TimelineViewModelTests.swift
  storyboards.swift
  strings.swift
Labels: feature

#61 Feature/24 Filter photos by categories
  PhotoMap/Coordinator.swift
  PhotoMap/Features/Category/Controllers/CategoryViewController.swift
  PhotoMap/Features/Category/Coordinators/CategoryCoordinator.swift
  PhotoMap/Features/Category/ViewModels/CategoryViewModel.swift
  PhotoMap/Features/Category/ViewModels/CategoryViewModelType.swift
  PhotoMap/Features/Timeline/Coordinators/TimelineCoordinator.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMapTests/ViewModels/CategoryViewModelTests.swift
  PhotoMapTests/ViewModels/TimelineViewModelTests.swift
Labels: feature

#62 Feature 59 load images from storage
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/Core/Base/Models/Marker.swift
  PhotoMap/Core/DI/DIContainer.swift
  PhotoMap/Features/Timeline/Controllers/MarkerCell.swift
  PhotoMap/Features/Timeline/Controllers/TimelineViewController.swift
  PhotoMap/Features/Timeline/Timeline.storyboard
  PhotoMap/Features/Timeline/ViewModels/TimelineCellViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModelType.swift
  PhotoMap/Resources/Localization/en.lproj/Localizable.strings
  PhotoMap/Resources/Localization/ru.lproj/Localizable.strings
  PhotoMap/Service/FileManagerService.swift
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMap/Service/FirestoreService/FirestoreServiceType.swift
  PhotoMapTests/Mocks/Services/FirestoreServiceMock.swift
  PhotoMapTests/ViewModels/TimelineCellViewModelTests.swift
  PhotoMapTests/ViewModels/TimelineViewModelTests.swift
  strings.swift
Labels: feature

#66 Feature/25 full photo screen
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/Extensions/UIScrollView+Ex.swift
  PhotoMap/Features/FullPhoto/Controllers/FullPhotoViewController.swift
  PhotoMap/Features/FullPhoto/Coordinators/FullPhotoCoordinator.swift
  PhotoMap/Features/FullPhoto/FullPhoto.storyboard
  PhotoMap/Features/FullPhoto/ViewModels/FullPhotoViewModel.swift
  PhotoMap/Features/FullPhoto/ViewModels/FullPhotoViewModelType.swift
  PhotoMap/Features/Timeline/Controllers/TimelineViewController.swift
  PhotoMap/Features/Timeline/Coordinators/TimelineCoordinator.swift
  PhotoMap/Features/Timeline/Timeline.storyboard
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModelType.swift
  PhotoMapTests/ViewModels/FullPhotoViewModelTests.swift
  storyboards.swift
  swiftgen.yml
Labels: feature

#63 Feature/15 load all photo for the shown area
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/Coordinator.swift
  PhotoMap/Core/Base/Errors/FirestoreError.swift
  PhotoMap/Core/Base/Models/Photo.swift
  PhotoMap/Core/Base/Models/PhotoAnnotation.swift
  PhotoMap/Core/Views/PhotoClusterView.swift
  PhotoMap/Core/Views/PhotoMarkerView.swift
  PhotoMap/Extensions/Date+Ex.swift
  PhotoMap/Extensions/String+Ex.swift
  PhotoMap/Features/Auth/Coordinators/AuthCoordinator.swift
  PhotoMap/Features/Map/Controllers/MapViewController.swift
  PhotoMap/Features/Map/Coordinators/MapCoordinator.swift
  PhotoMap/Features/Map/Map.storyboard
  PhotoMap/Features/Map/ViewModels/MapViewModel.swift
  PhotoMap/Features/Map/ViewModels/MapViewModelType.swift
  PhotoMap/Features/MapPhoto/Controllers/MapPhotoViewController.swift
  PhotoMap/Features/MapPhoto/Coordinators/MapPhotoCoordinator.swift
  PhotoMap/Features/MapPhoto/ViewModels/MapPhotoViewModel.swift
  PhotoMap/Features/More/Coordinators/MoreCoordinator.swift
  PhotoMap/Resources/Localization/en.lproj/Localizable.strings
  PhotoMap/Resources/Localization/ru.lproj/Localizable.strings
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMap/Service/FirestoreService/FirestoreServiceType.swift
  PhotoMapTests/Mocks/Services/FirestoreServiceMock.swift
  PhotoMapTests/ViewModels/MapViewModelTests.swift
  strings.swift
Labels: feature

#70 Feature/10 filter photos by categories
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/Core/Base/Coordinators/ImagePickerCoordinator.swift
  PhotoMap/Core/Base/Coordinators/ImagePickerProtocol.swift
  PhotoMap/Core/Base/Models/Photo.swift
  PhotoMap/Core/Base/Models/PhotoAnnotation.swift
  PhotoMap/Features/Map/Controllers/MapViewController.swift
  PhotoMap/Features/Map/Coordinators/MapCoordinator.swift
  PhotoMap/Features/Map/ViewModels/MapViewModel.swift
  PhotoMap/Features/Map/ViewModels/MapViewModelType.swift
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMapTests/Mocks/Services/FirestoreServiceMock.swift
  PhotoMapTests/ViewModels/MapViewModelTests.swift
Labels: feature

#73 Improvement/72 Combining models into a common entity
  PhotoMap.xcodeproj/project.pbxproj
  PhotoMap/Core/Base/Coordinators/ImagePickerCoordinator.swift
  PhotoMap/Core/Base/Models/Marker.swift
  PhotoMap/Core/Base/Models/Photo.swift
  PhotoMap/Core/Base/Models/PhotoAnnotation.swift
  PhotoMap/Core/Base/Models/PhotoDTO.swift
  PhotoMap/Core/Base/Models/PhotoDVO.swift
  PhotoMap/Core/Base/Models/UploadPhoto.swift
  PhotoMap/Features/FullPhoto/Coordinators/FullPhotoCoordinator.swift
  PhotoMap/Features/FullPhoto/ViewModels/FullPhotoViewModel.swift
  PhotoMap/Features/Map/Coordinators/MapCoordinator.swift
  PhotoMap/Features/Map/ViewModels/MapViewModel.swift
  PhotoMap/Features/Map/ViewModels/MapViewModelType.swift
  PhotoMap/Features/MapPhoto/Coordinators/MapPhotoCoordinator.swift
  PhotoMap/Features/MapPhoto/ViewModels/MapPhotoViewModel.swift
  PhotoMap/Features/MapPhoto/ViewModels/MapPhotoViewModelType.swift
  PhotoMap/Features/Timeline/Coordinators/TimelineCoordinator.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineCellViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModel.swift
  PhotoMap/Features/Timeline/ViewModels/TimelineViewModelType.swift
  PhotoMap/Service/FirestoreService/FirestoreService.swift
  PhotoMap/Service/FirestoreService/FirestoreServiceType.swift
  PhotoMapTests/Mocks/Services/FirestoreServiceMock.swift
  PhotoMapTests/ViewModels/CategoryViewModelTests.swift
  PhotoMapTests/ViewModels/FullPhotoViewModelTests.swift
  PhotoMapTests/ViewModels/MapPhotoViewModelTests.swift
  PhotoMapTests/ViewModels/MapViewModelTests.swift
  PhotoMapTests/ViewModels/TimelineCellViewModelTests.swift
  PhotoMapTests/ViewModels/TimelineViewModelTests.swift
Labels: improvement
